### ISSUE TITLE
on-close callback fails silently when it's not set properly

### ISSUE THREAD

**Issue by ayalaio** [stylefruits/gniazdo#12]
Callbacks fail silently when they are not set properly

Reproduce like this:

```
(def socket
  (ws/connect
     "ws://localhost:10081"
     :on-close #( prn "expecting two arguments, but receiving one" %1)
     :on-receive #( do-something %)))
```

I would expect something like this to be logged:
    ArityException Wrong number of args (2) passed to: core$eval1346$fn  clojure.lang.AFn.throwArity (AFn.java:437)

But is not.

Is this logged somewhere else?
Or where can I see the "Wrong number of args" exception?

**Comment by jstepien** [comment]
Thanks for filing an issue @aiionx! I've just pushed a test b96e91a72c765763e357ef47b152b53af19a143c covering an invalid arity scenario for `on-receive` and `on-connect`. In both cases `on-error` is called which allows you to react. Additionally, in [CI logs][logs] you can see a stack trace printed to the console, so the exceptions won't go unnoticed.

Unfortunately, I wasn't able to make it work for `on-close`. The exception doesn't show up anywhere, as if the underlying Jetty implementation was suppressing it. I think [this is where you could start looking for answers][close].

Let me know if this helps.

[logs]: https://travis-ci.org/stylefruits/gniazdo/jobs/74529126
[close]: https://github.com/eclipse/jetty.project/blob/6cabf8452e0e08f395a08916397ab6a7e602ff7c/jetty-websocket/websocket-common/src/main/java/org/eclipse/jetty/websocket/common/events/JettyListenerEventDriver.java#L98
