### ISSUE TITLE
pls add support for configuring websocket extensions

### ISSUE THREAD

**Issue by moizsj** [stylefruits/gniazdo#17]
for example, configuring the "permessage-deflate" extension in the ClientUpgradeRequest object. The object has an addExtension (or similar) method.

**Comment by jstepien** [comment]
@moizsj Pull requests are very welcome! Let us know if you need any help preparing a patch.

**Comment by moizsj** [comment]
Created a PR for the issue I filed.
https://github.com/stylefruits/gniazdo/pull/18
