### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by bago2k4** [stylefruits/gniazdo#20]
Hi,
it looks like you are missing the license in the project config file.

https://www.versioneye.com/Clojure/stylefruits:gniazdo/1.0.0

Thanks

**Comment by bago2k4** [comment]
Sorry i see now that you have it in the README. I "suggested" a license on versioneye since it's used by our systems to check packages integrity. Closing this issue.

**Comment by xsc** [comment]
Just FYI, I added a LICENSE to both the project.clj and the repository:
4be9d7b3d62c528a62251ddf7e654b0f94483979
